// Code generated by sumeru-import-gen; DO NOT EDIT.

package purchase

import (
	_ "sumeru_addons/product"
	_ "sumeru_addons/account"
	_ "sumeru_addons/purchase/models"
	_ "sumeru_addons/purchase/services"
)
