// Code generated by sumeru-import-gen; DO NOT EDIT.

package stock

import (
	_ "sumeru_addons/product"
	_ "sumeru_addons/stock/models"
	_ "sumeru_addons/stock/services"
	_ "sumeru_addons/stock/controllers"
)
