// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("account",
		&AccountAccount{},
		&AccountFullReconcile{},
		&AccountInvoiceReport{},
		&AccountJournal{},
		&AccountMove{},
		&AccountMoveLine{},
		&AccountPartialReconcile{},
		&AccountPayment{},
		&AccountPaymentTerm{},
		&AccountTax{},
		&AccountTaxRepartitionLine{},
	)
}
