// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("account",
		&AccountAccount{},
		&AccountAnalyticAccount{},
		&AccountAnalyticPlan{},
		&AccountBankStatement{},
		&AccountBankStatementLine{},
		&AccountFiscalPosition{},
		&AccountFiscalPositionTax{},
		&AccountFullReconcile{},
		&AccountGroup{},
		&AccountInvoiceReport{},
		&AccountJournal{},
		&AccountMove{},
		&AccountMoveLine{},
		&AccountPartialReconcile{},
		&AccountPayment{},
		&AccountPaymentTerm{},
		&AccountPaymentTermLine{},
		&AccountReconcileModel{},
		&AccountTax{},
		&AccountTaxRepartitionLine{},
	)
}
