// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("account",
		&AccountAccount{},
		&AccountAnalyticAccount{},
		&AccountAnalyticPlan{},
		&AccountAsset{},
		&AccountBankStatement{},
		&AccountBankStatementLine{},
		&AccountBudget{},
		&AccountDeferredSchedule{},
		&AccountFiscalPosition{},
		&AccountFiscalPositionTax{},
		&AccountFullReconcile{},
		&AccountGroup{},
		&AccountInvoiceReport{},
		&AccountJournal{},
		&AccountLockDate{},
		&AccountMove{},
		&AccountMoveAudit{},
		&AccountMoveLine{},
		&AccountPartialReconcile{},
		&AccountPayment{},
		&AccountPaymentTerm{},
		&AccountPaymentTermLine{},
		&AccountReconcileModel{},
		&AccountRecurringTemplate{},
		&AccountTax{},
		&AccountTaxRepartitionLine{},
		&AccountTaxReturn{},
	)
}
