// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import (
	basemodels "sumeru/addons/base/models"
)

// CoreCompany → core.company
type CoreCompany = basemodels.CoreCompany

// CoreCountry → core.country
type CoreCountry = basemodels.CoreCountry

// CorePartner → core.partner
type CorePartner = basemodels.CorePartner

