// Code generated by sumeru-import-gen; DO NOT EDIT.

package sale_crm

import (
	_ "sumeru_addons/crm"
	_ "sumeru_addons/sale"
	_ "sumeru_addons/sale_crm/models"
	_ "sumeru_addons/sale_crm/services"
)
