// Code generated by sumeru-import-gen; DO NOT EDIT.

package crm

import (
	_ "sumeru/addons/base"
	_ "sumeru/addons/contacts"
	_ "sumeru/addons/geo"
	_ "sumeru/addons/i18n"
	_ "sumeru_addons/iap"
	_ "sumeru/addons/im"
	_ "sumeru/addons/automation"
	_ "sumeru_addons/utm"
	_ "sumeru_addons/crm/models"
	_ "sumeru_addons/crm/services"
	_ "sumeru_addons/crm/wizard"
)
