// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import (
	basemodels "sumeru/addons/base/models"
)

// CoreCompany → core.company
type CoreCompany = basemodels.CoreCompany

// CorePartner → core.partner
type CorePartner = basemodels.CorePartner

// CoreUser → core.user
type CoreUser = basemodels.CoreUser

