// Code generated by sumeru-import-gen; DO NOT EDIT.

package account

import (
	_ "sumeru/addons/contacts"
	_ "sumeru_addons/product"
	_ "sumeru_addons/account/models"
	_ "sumeru_addons/account/services"
	_ "sumeru_addons/account/wizard"
	_ "sumeru_addons/account/controllers"
)
