// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import (
	basemodels "sumeru/addons/base/models"
	crmmodels "sumeru_addons/crm/models"
	productmodels "sumeru_addons/product/models"
)

// CoreCompany → core.company
type CoreCompany = basemodels.CoreCompany

// CorePartner → core.partner
type CorePartner = basemodels.CorePartner

// CoreUser → core.user
type CoreUser = basemodels.CoreUser

// CrmLead → crm.lead
type CrmLead = crmmodels.CrmLead

// ProductProduct → product.product
type ProductProduct = productmodels.ProductProduct

