// Code generated by sumeru-import-gen; DO NOT EDIT.

package sale

import (
	_ "sumeru/addons/contacts"
	_ "sumeru_addons/product"
	_ "sumeru_addons/crm"
	_ "sumeru_addons/sale/models"
	_ "sumeru_addons/sale/services"
)
