// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("stock",
		&StockLocation{},
		&StockLot{},
		&StockMove{},
		&StockMoveLine{},
		&StockOrderpoint{},
		&StockPicking{},
		&StockPickingType{},
		&StockQuant{},
		&StockRule{},
		&StockScrap{},
		&StockWarehouse{},
	)
}
