// Code generated by sumeru-import-gen; DO NOT EDIT.

package wizard

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("crm",
		&CrmLead2Opportunity{},
		&CrmLead2OpportunityMass{},
		&CrmLeadLost{},
		&CrmLeadPlsUpdate{},
		&CrmMergeOpportunity{},
	)
}
