// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import "sumeru/core/sdk"

func init() {
	sdk.MustRegister("crm",
		&CrmActivityReport{},
		&CrmLead{},
		&CrmLeadScoringFrequency{},
		&CrmLeadScoringFrequencyField{},
		&CrmLostReason{},
		&CrmRecurringPlan{},
		&CrmStage{},
		&CrmTag{},
		&CrmTeam{},
		&CrmTeamMember{},
	)
}
