// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import (
	basemodels "sumeru/addons/base/models"
	geomodels "sumeru/addons/geo/models"
	i18nmodels "sumeru/addons/i18n/models"
	utmmodels "sumeru_addons/utm/models"
)

// CoreCompany → core.company
type CoreCompany = basemodels.CoreCompany

// CoreCountry → core.country
type CoreCountry = geomodels.CoreCountry

// CoreCountryState → core.country.state
type CoreCountryState = geomodels.CoreCountryState

// CoreCurrency → core.currency
type CoreCurrency = geomodels.CoreCurrency

// CoreLang → core.lang
type CoreLang = i18nmodels.CoreLang

// CorePartner → core.partner
type CorePartner = basemodels.CorePartner

// CoreUser → core.user
type CoreUser = basemodels.CoreUser

// UtmCampaign → utm.campaign
type UtmCampaign = utmmodels.UtmCampaign

// UtmMedium → utm.medium
type UtmMedium = utmmodels.UtmMedium

// UtmSource → utm.source
type UtmSource = utmmodels.UtmSource

