// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import (
	basemodels "sumeru/addons/base/models"
	mailmodels "sumeru/addons/mail/models"
	utmmodels "sumeru_addons/utm/models"
)

// CoreCompany → core.company
type CoreCompany = basemodels.CoreCompany

// CoreCountry → core.country
type CoreCountry = basemodels.CoreCountry

// CoreCountryState → core.country.state
type CoreCountryState = basemodels.CoreCountryState

// CoreCurrency → core.currency
type CoreCurrency = basemodels.CoreCurrency

// CoreLang → core.lang
type CoreLang = basemodels.CoreLang

// CorePartner → core.partner
type CorePartner = basemodels.CorePartner

// CoreUser → core.user
type CoreUser = basemodels.CoreUser

// MailActivity → mail.activity
type MailActivity = mailmodels.MailActivity

// UtmCampaign → utm.campaign
type UtmCampaign = utmmodels.UtmCampaign

// UtmMedium → utm.medium
type UtmMedium = utmmodels.UtmMedium

// UtmSource → utm.source
type UtmSource = utmmodels.UtmSource

