// Code generated by sumeru-import-gen; DO NOT EDIT.

package website_crm

import (
	_ "sumeru_addons/utm"
	_ "sumeru_addons/crm"
	_ "sumeru_addons/website_crm/models"
	_ "sumeru_addons/website_crm/services"
)
